# Generated by Django 4.2.3 on 2023-09-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post',
            field=models.ImageField(blank=True, null=True, upload_to='Postes'),
        ),
    ]
