# Generated by Django 4.2.3 on 2023-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapi', '0002_alter_userprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='E:\\Django\\social\\media\\profile_pictures\\defaultuser.png', null=True, upload_to='profile_pictures/'),
        ),
    ]
